Add setup directory with scripts that automate deployment and benchmarking
daos-stack/google-cloud-daos pull request #7
Opened 2021-10-07 16:01 UTC by lsitkiew

Signed-off-by: Łukasz Sitkiewicz <lukasz.sitkiewicz@intel.com>

2021-10-11 05:01 UTC, cboneti requested changes
I love that you are automating the io500 run here. I would suggest that you pair that with the other change, where you move it to a io500 example and you do anything specific to this use case there (hence, not binding the images to that use case).

2021-10-11 08:37 UTC, lsitkiew commented on images/scripts/configure_ssh.sh
> +sed -i '/^PermitRootLogin/s/no/yes/' /etc/ssh/sshd_config && sudo systemctl restart sshd
It is not intended to be merged in this way. I'm aware that it's not safe. We needed this workaround due to the instability of the gcloud commands. I did this PR to start the review process while I'm working on better way to do this. I will change this.

2021-10-15 13:24 UTC, johannlombardi commented on terraform/examples/io500/clean.sh
> +done
Not sure what the use case for this script is. Could you please elaborate?

2021-10-15 13:25 UTC, johannlombardi commented on terraform/examples/io500/setup_io500.sh
> +done
Maybe we could use pdsh or even better clush (see clustershell) for this? We could fix this after the patch is landed through.

2021-10-15 13:26 UTC, johannlombardi commented on terraform/examples/io500/setup_io500.sh
> +    if [ $(dmg -i system query -v | grep Joined | wc -l) -eq ${NUMBER_OF_SERVERS_INSTANCES} ]
This could use the -j for the json format to be more reliable.

2021-10-15 13:27 UTC, johannlombardi commented on terraform/examples/io500/setup_io500.sh
> +
Shall we set -x to fail if any command fails below?

2021-10-15 13:28 UTC, johannlombardi commented on terraform/examples/io500/setup_io500.sh
> +export FI_UNIVERSE_SIZE=1024
We should set this to a higher value like 16383.

2021-10-18 16:20 UTC, merged